language: cpp
os: linux
dist: xenial

branches:
  except: /^appveyor.*$/

git:
  autocrlf: false
  depth: 5

addons:
  apt:
    packages:
      - libsdl2-dev
      - libvorbis-dev
      - libflac-dev
      - libvpx-dev
      - libglu1-mesa-dev
      - libgtk2.0-dev
      - clang
      - llvm-dev

jobs:
  include:
  - os: linux
    name: "Linux GCC"
    compiler: gcc
    script:
    - make -j2 duke3d sw blood rr exhumed tools
  - os: linux
    name: "Linux Clang"
    compiler: clang
    script:
    - make -j2 CLANG=1 duke3d sw blood rr exhumed tools
  - os: osx
    name: "macOS"
    osx_image: xcode10.1
    script:
    - brew install sdl2 libogg libvorbis flac libvpx make
    - gmake -j2 duke3d sw blood rr exhumed tools

notifications:
  email: false
