language: cpp
os: linux
dist: xenial

branches:
  except: /^appveyor.*$/

git:
  autocrlf: false
  depth: 5

addons:
  apt:
    packages:
      - libvorbis-dev
      - libflac-dev
      - libvpx-dev
      - libglu1-mesa-dev
      - libgtk2.0-dev
      - clang

jobs:
  include:
  - os: linux
    name: "Linux GCC"
    compiler: gcc
    script:
    - make -kj2
  - os: linux
    name: "Linux Clang"
    compiler: clang
    script:
    - make -kj2 CLANG=1
  - os: osx
    name: "macOS"
    osx_image: xcode10.1
    script:
    - brew install libvorbis flac libvpx make
    - gmake -kj2

notifications:
  email: false
