language: cpp
os: linux
dist: xenial

branches:
  except: /^appveyor.*$/

git:
  autocrlf: false
  depth: 5

addons:
  apt:
    packages:
      - libvorbis-dev
      - libflac-dev
      - libvpx-dev
      - libglu1-mesa-dev
      - libgtk2.0-dev
      - clang

jobs:
  include:
  - os: linux
    compiler: gcc
    script:
    - make -kj2

  - os: linux
    compiler: clang
    - make -kj2 CLANG=1

  - os: osx
    osx_image: xcode10.1
    - brew install libvorbis flac libvpx make
    - gmake -kj2

notifications:
  email: false
